typography_spectrum: 0.41351298871450126
color:
  brandStrength: 0.5666029816493392
  lightness: 0.7198344795033336
  saturation: 0.7516153086908162
  rhythmicContrast: 0.5852135811001062
github: true
opengraph:
  type: 'https://www.facebook.com/KyawKyawThetOfficial/'
  appId: mr.lampcrazy
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/72d29e47-2917-4d82-a89f-ae9cdf93897d.jpg
layout_spectrum: 0.7233594129793346
author:
  name: Kyaw Kyaw Thet
  email: kktstudy@gmail.com
  url: 'https://www.facebook.com/KyawKyawThetOfficial/'
logo: null
name: endless lessons by KKT
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/05807a53-b153-4352-9c0d-c0358396bbca.jpg
title: ' ေကာင္းနိုးရာရာမ်ား'
